env:
  es6: true
extends:
  - standard-with-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  require-await: off
  '@typescript-eslint/require-await': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/strict-boolean-expressions': off
