version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd scripts
      - ./clean.sh
      - ./build-modules.sh
      - ./prepare-production-dependencies.sh
      - cd ..
      - aws cloudformation package --template-file infrastructure/template.yml --s3-bucket jumoresques-lambda-bucket --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
