version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
#     a workaround for timestamps before 1980
      - find ./node_modules -type f -exec touch {} +
      - mkdir common_layer
      - mkdir common_layer/nodejs
      - cp -RL node_modules common_layer/nodejs
      - aws cloudformation package --template-file template.yml --s3-bucket jumoresques-lambda-bucket --output-template-file packaged-template.yml
      - cd skill
      - npm run build
      - ask deploy
artifacts:
  files:
    - packaged-template.yml
