version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
      - aws cloudformation package --template-file template.yml --s3-bucket jumoresques-lambda-bucket --output-template-file output-template.yml
artifacts:
  type: zip
  files:
    - template.yml
    - output-template.yml
