AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fetches jumoresques and reads them out loud in funny voice
Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: dist/common
      Description: Common functions and domain objects
      LayerName: CommonLayer
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: node_modules
      Description: node_modules directory containing all dependencies
      LayerName: NodeModulesLayer
  RefreshJumoresquesHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: dist/handlers/vk
      Layers:
        - !Ref CommonLayer
        - !Ref NodeModulesLayer
      Events:
        Refresh:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 hour)'
            Name: RefreshJumoresquesSchedule
            Description: Triggers refresh handler for jumoresques
            Enabled: true
#  AlexaSkillHandler:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: alexa-skill-handler.handler
#      Runtime: nodejs12.x
#      CodeUri: ./dist/functions/handlers
#      Events:
#        Refresh:
#          Type: Schedule
#          Properties:
#            Schedule: 'rate(1 hour)'
#            Name: RefreshJumoresquesSchedule
#            Description: Triggers refresh handler for jumoresques
#            Enabled: true
