env:
  es6: true
plugins:
  - '@typescript-eslint'
rules:
  require-await: off
  '@typescript-eslint/require-await': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/strict-boolean-expressions': off
