AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fetches jumoresques and reads them out loud in funny voice
Parameters:
  Env:
    Type: String
Resources:
  Mp3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt Mp3Sqs.Arn
    DependsOn: Mp3SqsPolicy
  Mp3IdDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: value
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: value
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  Mp3Sqs:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt Mp3DeadLetterSqs.Arn
        maxReceiveCount: 1
  Mp3DeadLetterSqs:
    Type: AWS::SQS::Queue
  Mp3SqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource:
              - !GetAtt Mp3Sqs.Arn
            Action:
              - SQS:SendMessage
      Queues:
        - !Ref Mp3Sqs
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: ../src/layers/common
  PropertiesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: ../src/layers/properties
  AlexaSkillIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: alexaSkillExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: s3JumoresquesReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::jumoresques/jumoresques.mp3
        - PolicyName: secretManagerJumoresquesReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-west-1:403020287921:secret:vk-BcAwdu
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: amzn1.ask.skill.3eff6c78-ec5a-4d43-80ea-430bbe3d37d1
  PollyReadOnlyAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - polly:SynthesizeSpeech
            Resource: '*'
      Roles:
        - !Ref RefreshJumoresquesHandlerRole
      PolicyName: PollyReadOnlyAccessPolicy
  RefreshJumoresquesHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: ../src/handlers/vk
      Layers:
        - !Ref CommonLayer
        - !Ref PropertiesLayer
      Environment:
        Variables:
          BUCKET: !Ref Mp3Bucket
          ENVIRONMENT: !Ref Env
          FUNCTION_NAME: refresher
      Policies:
        - S3WritePolicy:
            BucketName:
              !Ref Mp3Bucket
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt Mp3Sqs.QueueName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-west-1:403020287921:secret:vk-BcAwdu
      Events:
        Refresh:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 hour)'
            Description: Triggers refresh handler for jumoresques
            Enabled: true
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: ../src/handlers/alexa
      Layers:
        - !Ref CommonLayer
        - !Ref PropertiesLayer
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          ENVIRONMENT: !Ref Env
          FUNCTION_NAME: alexa-handler
  YandexMp3UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.upload
      Runtime: nodejs12.x
      CodeUri: ../src/handlers/yandex
      Layers:
        - !Ref CommonLayer
        - !Ref PropertiesLayer
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              !GetAtt Mp3IdDynamoTable.Arn
        - S3ReadPolicy:
            BucketName:
              !Ref Mp3Bucket
        - SQSPollerPolicy:
            QueueName:
              !GetAtt Mp3Sqs.QueueName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-west-1:403020287921:secret:yandex-TYwPDV
      Environment:
        Variables:
          TABLE: !Ref Mp3IdDynamoTable
          BUCKET: !Ref Mp3Bucket
          ENVIRONMENT: !Ref Env
          FUNCTION_NAME: yandex-upload-handler
      Events:
        JumoresquesUploadEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Mp3Sqs.Arn
            BatchSize: 1
  YandexMp3PlayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.playSound
      Runtime: nodejs12.x
      CodeUri: ../src/handlers/yandex
      Layers:
        - !Ref CommonLayer
        - !Ref PropertiesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !GetAtt Mp3IdDynamoTable.Arn
      Environment:
        Variables:
          TABLE: !Ref Mp3IdDynamoTable
          ENVIRONMENT: !Ref Env
          FUNCTION_NAME: yandex-alisa-handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /
