AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fetches jumoresques and reads them out loud in funny voice
Parameters:
  Env:
    Type: String
Resources:
  Mp3Bucket:
    Type: AWS::S3::Bucket
  Mp3IdDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: value
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: value
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  Mp3Sqs:
    Type: AWS::SQS::Queue
  CommonModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: ../common_layer
  RefreshJumoresquesHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ../dist/handlers/vk
      Layers:
        - !Ref CommonModulesLayer
      Environment:
        Variables:
          BUCKET: !Ref Mp3Bucket
      Policies:
        - S3ReadPolicy:
            BucketName:
              !Ref Mp3Bucket
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt Mp3Sqs.QueueName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-west-1:403020287921:secret:vk-BcAwdu
      Events:
        Refresh:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 hour)'
            Name: RefreshJumoresquesSchedule
            Description: Triggers refresh handler for jumoresques
            Enabled: true
  AlexaSkillIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: alexaSkillExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: s3JumoresquesReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::jumoresques/jumoresques.mp3
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-west-1:403020287921:secret:vk-BcAwdu
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/handlers/alexa
      Handler: index.handler
      Layers:
        - !Ref CommonModulesLayer
      Runtime: nodejs12.x
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 128
      Timeout: 60
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: amzn1.ask.skill.3eff6c78-ec5a-4d43-80ea-430bbe3d37d1
  YandexMp3UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.upload
      CodeUri: ../dist/handlers/yandex
      Runtime: nodejs12.x
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              !GetAtt Mp3IdDynamoTable.Arn
        - S3ReadPolicy:
            BucketName:
              !Ref Mp3Bucket
        - SQSPollerPolicy:
            QueueName:
              !GetAtt Mp3Sqs.QueueName
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-west-1:403020287921:secret:yandex-TYwPDV
      Environment:
        Variables:
          TABLE: !Ref Mp3IdDynamoTable
          BUCKET: !Ref Mp3Bucket
      Events:
        JumoresquesUploadEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Mp3Sqs.Arn
            BatchSize: 1
  YandexMp3PlayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.playSound
      CodeUri: ../dist/handlers/yandex
      Runtime: nodejs12.x
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !GetAtt Mp3IdDynamoTable.Arn
      Environment:
        Variables:
          TABLE: !Ref Mp3IdDynamoTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /
